benchmark_name: veritas
benchmark_kwargs:
  variant: longitudinal
  data_path: /mnt/vast/home/mk79honu/Veritas/baselines/data/veritas_release/veritas_longitudinal_2020_q1_2025_q4
  label_scheme: 7  # 3 for 3-class (Intact/Unknown/Compromised), 7 for 7-class with uncertainty levels
fact_checker_kwargs:
  decompose: false
  decontextualize: false
  filter_check_worthy: false
  interpret: false
  max_iterations: 3
  max_result_len: 64000
  procedure_variant: summary/dynamic
llm: gpt_52
llm_kwargs:
  temperature: 0.01
n_samples: 10
random_sampling: false
sample_ids: null
allowed_actions:
- search
- geolocate
tools_config:
  searcher:
    limit_per_search: 3
    max_result_len: 200000
    search_config:
      google:
  geolocator:
n_workers: 1
print_log_level: info
